[window]
opacity = 0.8
blur = true

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
size = 15

[colors]
cursor = { text = "CellBackground", cursor = "#dcdfe4" }

  [colors.primary]
  background = "#282c34"
  foreground = "#dcdfe4"

  [colors.normal]
  black = "#747e85"
  red = "#e06c75"
  green = "#98c379"
  yellow = "#e5c07b"
  blue = "#61afef"
  magenta = "#c678dd"
  cyan = "#56b6c2"
  white = "#dcdfe4"
